### ISSUE TITLE
Error on gpg card-status

### ISSUE THREAD

**Issue by jpathy** [alonbl/gnupg-pkcs11-scd#10]
Hello,
I am on GnuPG version 2.1.15(shipped by ubuntu zesty)
I get `gpg: OpenPGP card not available: Bad session key` on card-edit or card-status. Currently using the master branch.Only the 7.4 release works(with emulate-openpgp); other versions give same error.

**Comment by alonbl** [comment]
interesting, can you please send me debug log?
kill gpg-agent
add the following to gnupg-pkcs11-scd configuration:

debug-all
verbose
log-file /tmp/g.log

and execute:

 gpg --card-status

then immediately copy the log and attach.

**Comment by jpathy** [comment]
I have attached the log here. 
[log.txt](https://github.com/alonbl/gnupg-pkcs11-scd/files/1340414/log.txt)

**Comment by alonbl** [comment]
Can I have your gnupg-pkcs11-scd config? I guess you have the legacy workarounds of key assignment set...

**Comment by jpathy** [comment]
Yes, i am using them, otherwise the keys doesn't show up in my card-status and addcardkey doesn't work.

**Comment by alonbl** [comment]
On 28 September 2017 at 14:36, jpathy <notifications@github.com> wrote:

> Yes, i am using them, otherwise the keys doesn't show up in my card-status
> and addcardkey doesn't work.
>
> —
>

Can you please remove them, kill gpg-agent and send me the log?
Based on the log you sent it should have worked.

**Comment by jpathy** [comment]
Ok, i guess the instructions in the man page should not say >=2.1.19 :( For subkeys `addcardkey` is not what we should issue; `addkey` should be issued and follow the instructions in the part for >=2.1.19.
For primary key i am not sure what should be done, though. `--full-generate-key` is not in this version and `--full-gen-key` have no option to add existing key with their fingerprint.

Here is the log with `addcardkey` :

    gnupg-pkcs11-scd[25431]: chan_0 -> S KEY-ATTR 1 1 1 2048 0
    gnupg-pkcs11-scd[25431]: chan_0 -> S KEY-ATTR 2 1 1 2048 0
    gnupg-pkcs11-scd[25431]: chan_0 -> S KEY-ATTR 3 1 1 2048 0
    gnupg-pkcs11-scd[25431]: chan_0 -> OK
    gnupg-pkcs11-scd[25431]: chan_0 <- CHECKPIN XXXXXXXXXXXXXXXXXXXXXXXXX
    gnupg-pkcs11-scd[25431]: chan_0 -> OK
    gnupg-pkcs11-scd[25431]: chan_0 <- GENKEY --timestamp=20170928T114046 --force 1
    gnupg-pkcs11-scd[25431]: chan_0 -> ERR 19 Bad session key <Unspecified source>
    gnupg-pkcs11-scd[25431]: chan_0 <- RESTART
    gnupg-pkcs11-scd[25431]: chan_0 -> OK

Edit: **TLDR**; For my purpose of adding subkeys, it _works_ with addkey with existing fingerprint.

**Comment by alonbl** [comment]
On 28 September 2017 at 14:58, jpathy <notifications@github.com> wrote:

> Ok, i guess the instructions in the man page should not say >=2.1.19 :(
> For subkeys addcardkey is not what we should issue; addkey should be
> issued and follow the instructions in the part for >=2.1.19.
> For primary key i am not sure what should be done, though.
> --full-generate-key is not in this version and --full-gen-key have no
> option to add existing key with their fingerprint.
>
> Here is the log with addcardkey :
>

The gnupg upstream broke the scdaemon protocol several times during the 2.1
development.
Only in 2.1.19 I succeeded to add a patch to be able to use scdaemon with
the --full-gen-key.
I just rebuilt gnupg out of 2.1.19 and I do see this command available with
option 13 (exiting key).

Thanks for reminding me this story...

For now in 2.1.15 please continue to work with the old version, I could not
support 2.1.x series in both modes.

**Comment by alonbl** [comment]
Hi,
I am closing this as 2.1.19 is working.
Alon
