### ISSUE TITLE
Ambiguous license

### ISSUE THREAD

**Issue by flyn-org** [alonbl/gnupg-pkcs11-scd#12]
I am trying to package gnupg-pkcs11-scd for Fedora [1]. The COPYING file provided with the gnupg-pkcs11-scd is a bit ambiguous. It lists six licenses:

BSD
    Seems to be the primary license. The code in gnupg-pkcs11-scd/ bears this license in comments.
    The code in gnupg-pkcs11-scd-proxy/ does not bear such comments. What license covers this code?

All rights reserved
    Applies to "pkcs11-helper." What is that? Is any component of gnupg-pkcs11-scd not open source?

m4 Macros License
    Is this necessary?

OpenSSL license
    This code is not shipped with gnupg-pkcs11-scd. Why is this needed?

GNUTLS license
    This code is not shipped with gnupg-pkcs11-scd. Why is this needed?

libgcrypt license
    This code is not shipped with gnupg-pkcs11-scd. Why is this needed?

[1] https://bugzilla.redhat.com/show_bug.cgi?id=706199

**Comment by alonbl** [comment]
> I am trying to package gnupg-pkcs11-scd for Fedora [1]. The COPYING file provided with the gnupg-pkcs11-scd is a bit ambiguous. It lists six licenses:

it is not six licenses... In the past people asked to have credit for each of 3rd party used.

> 
> BSD
> Seems to be the primary license. The code in gnupg-pkcs11-scd/ bears this license in comments.
> The code in gnupg-pkcs11-scd-proxy/ does not bear such comments. What license covers this code?

I saw legal documentation that claims that the license file in package is sufficient to be applied to all package files, no need to mark each file.
Anyway, added.

> All rights reserved
> Applies to "pkcs11-helper." What is that? Is any component of gnupg-pkcs11-scd not open source?

This is an old one.. of pkcs11-helper, I will remove this line from pkcs11-helper as well.

> m4 Macros License
> OpenSSL license
> GNUTLS license
> libgcrypt license
> This code is not shipped with gnupg-pkcs11-scd. Why is this needed?

In the past I was asked to add these for any 3rd party component, similar to other projects we have in opensc and openvpn, these explicitly specify that the license is of the 3rd party, I do not understand how can this be interpreted as license of this package.

Fixes at cb2f730
