### ISSUE TITLE
Unable to work with eToken

### ISSUE THREAD

**Issue by PlatinumDragon** [alonbl/gnupg-pkcs11-scd#18]
I'm  trying to generate keys on Alladin eToken pro 64k using gpg --card-edit and I get `Key generation failed: Bad session key`
gpg (GnuPG) 2.2.15
gnupg-pkcs11-scd 0.9.2

**Comment by alonbl** [comment]
Please send debug logs of the gnupg-pkcs11-scd.

**Comment by PlatinumDragon** [comment]
https://pastebin.com/6GyTnyqy

**Comment by alonbl** [comment]
Thanks!
Please paste configuration.

**Comment by PlatinumDragon** [comment]
```
log-file /home/admin/pkcs11log
verbose
providers p1
provider-p1-library /usr/lib/libeToken.so
openpgp-sign 799D38BE073EFB38CF38322F752740F13BD419C6
openpgp-encr 799D38BE073EFB38CF38322F752740F13BD419C6
openpgp-auth 799D38BE073EFB38CF38322F752740F13BD419C6
```

**Comment by alonbl** [comment]
I believe you followed the gnupg-2.0 sequence while you have you have
gnupg-2.1.
Please follow the gnupg-2.1 sequence[1]

[1]
https://github.com/alonbl/gnupg-pkcs11-scd/blob/master/gnupg-pkcs11-scd/gnupg-pkcs11-scd.1
