### ISSUE TITLE
Please change tagging convention

### ISSUE THREAD

**Issue by kloczek** [alonbl/gnupg-pkcs11-scd#22]
tar ball from https://github.com/alonbl/gnupg-pkcs11-scd//archive/gnupg-pkcs11-scd-0.9.2.tar.gz has as base directory gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/.
Please use just <version> as tag next time.

**Comment by alonbl** [comment]
I am unsure what you refer to, release[1] tarball is ok, please learn how to use github release artifacts.

[1] https://github.com/alonbl/gnupg-pkcs11-scd/releases/download/gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-0.9.2.tar.bz2

**Comment by kloczek** [comment]
Conten is OK.
Issue is that base directory inside of the tar ball generated pit of tag (not release) contains two times rpeated name of the package.
<pre>[tkloczko@barrel SPECS]$ rm gnupg-pkcs11-scd-0.9.2.tar.gz
[tkloczko@barrel SPECS]$ wget https://github.com/alonbl/gnupg-pkcs11-scd//archive/gnupg-pkcs11-scd-0.9.2.tar.gz
--2019-10-14 21:13:22--  https://github.com/alonbl/gnupg-pkcs11-scd//archive/gnupg-pkcs11-scd-0.9.2.tar.gz
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/alonbl/gnupg-pkcs11-scd/tar.gz/gnupg-pkcs11-scd-0.9.2 [following]
--2019-10-14 21:13:22--  https://codeload.github.com/alonbl/gnupg-pkcs11-scd/tar.gz/gnupg-pkcs11-scd-0.9.2
Resolving codeload.github.com (codeload.github.com)... 140.82.113.9
Connecting to codeload.github.com (codeload.github.com)|140.82.113.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘gnupg-pkcs11-scd-0.9.2.tar.gz’

gnupg-pkcs11-scd-0.9.2.tar.gz                  [ &lt;=&gt;                                                                                  ]  46.15K   244KB/s    in 0.2s    

2019-10-14 21:13:23 (244 KB/s) - ‘gnupg-pkcs11-scd-0.9.2.tar.gz’ saved [47255]

[tkloczko@barrel SPECS]$ tar tzf gnupg-pkcs11-scd-0.9.2.tar.gz
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/.gitignore
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/AUTHORS
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/COPYING
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/ChangeLog
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/INSTALL
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/Makefile.am
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/README
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/THANKS
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/configure.ac
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/Makefile.am
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/Makefile.am
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/README.build
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/changelog
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/compat
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/control
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/copyright.m4
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/rules
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/debian/watch
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/rpm/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/rpm/Makefile.am
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/distro/rpm/gnupg-pkcs11-scd.spec.in
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-proxy/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-proxy/Makefile.am
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-proxy/gnupg-pkcs11-scd-proxy-server.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-proxy/gnupg-pkcs11-scd-proxy.1
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-proxy/gnupg-pkcs11-scd-proxy.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd-proxy/gnupg-pkcs11-scd-proxy.service.in.in
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/Makefile.am
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/command.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/command.h
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/common.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/common.h
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/dconfig.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/dconfig.h
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/encoding.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/encoding.h
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/gnupg-pkcs11-scd.1
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/gnupg-pkcs11-scd.conf.example
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/keyutil.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/keyutil.h
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/gnupg-pkcs11-scd/scdaemon.c
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/m4/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/m4/ax_pthread.m4
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/misc/
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/misc/init-token-gnutls.sh
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/misc/init-token-openssl.sh
gnupg-pkcs11-scd-gnupg-pkcs11-scd-0.9.2/misc/pinentry-file
</pre>
This because you are adding name of the repository to the tag.

**Comment by alonbl** [comment]
I will set my tags in any method I like, tags are internal to source code management.

github creates the source tarball per tag automatically based on whatever algorithm it likes, there is no way to block this automatic creation of tarballs, you should *not* use this tarball.

In each release there is a formal source tarball for you to use created by `make dist`, you should use this tarball, once again, the directory name has nothing to do with tag name, it is the autotools convention of package name and version.

Alternatively, if you want to access tags, clone the repository and use it directly.

**Comment by kloczek** [comment]
Thank you very much for your understanding that some people are watching in tags changes to run automaric packakign process.
With YourWay(tm) of tagging you are no longer now adds some overhead to that kind of processes.

One more time .. thank you very much.

**Comment by alonbl** [comment]
It is not my way, many projects behaves the same.
Instead of monitoring this autogen tarball, you can monitor the formal
source tarball as other projects are doing.

**Comment by kloczek** [comment]
As I wrote before again .. thank you very much for your understanding.

PS. I woud accept your reply if you would have some exect arguments to stick to that pattern however your only argument is "I'm using it because I want it".

**Comment by alonbl** [comment]
I truly don’t get it. Assuming you are interested in a new release why are
you trying to couple with github feature? Let’s assume that the project was
hosted in other hosting service and release source tarballs were published
into webdav mirror, what would you argue then? That all projects must be
hosted at github so you can use your way of detection? You are trying to
couple distribution concepts with source concepts and hosting technology
(github) with consumption.

בתאריך יום ג׳, 15 באוק׳ 2019 ב-9:35 מאת Tomasz Kłoczko <
notifications@github.com>:
