### ISSUE TITLE
Incompatibility with GnuPG 2 generates bad signatures

### ISSUE THREAD

**Issue by mbechler** [alonbl/gnupg-pkcs11-scd#3]
GnuPG 2 (at least recent versions) sends both the algorithm OID as prefix in SETDATA as well as the hash algorithm in PKSIGN. This results in gnupg-pkcs11-scd adding yet another instance of the algorithm OID to the buffer which will then be part of the signed data.

Forcing inject = INJECT_NONE in cmd_pksign fixes the issue for me, but for backward compatibility I guess one would have to add an actual check for the hash/data size.

**Comment by mbechler** [comment]
And another one in pkdecrypt: Looks like gnupg now expects padding if not indicated otherwise (making decryption fail).

```
@@ -1283,6 +1285,7 @@
 				&ptext_len
 			)
 		)) != GPG_ERR_NO_ERROR ||
+		(error = assuan_write_status (ctx, "PADDING", "0")) != GPG_ERR_NO_ERROR ||
 		(error = assuan_send_data(ctx, ptext, ptext_len)) != GPG_ERR_NO_ERROR
 	) {
 		goto cleanup;
```

**Comment by alonbl** [comment]
Thank you!
I hope I can check out this during this weekend.

**Comment by alonbl** [comment]
Hi,
Can you please checkout gnupg-2.1 branch and see if it works for you?
Thanks!

**Comment by mbechler** [comment]
Thanks for your work. Sorry for the delay.

The corruption while signing is gone but now produces unsupported algorithm as we get into the first branch (hash parameter set) and the hash size won't match as the OID prefix is already included.

Patch adding explicit branches for these cases
[gnupg-pkcs11-scd-hashcomp.patch.txt](https://github.com/alonbl/gnupg-pkcs11-scd/files/693729/gnupg-pkcs11-scd-hashcomp.patch.txt)

**Comment by alonbl** [comment]
Thanks!
Can you please send this as pull request?

**Comment by alonbl** [comment]
Merged, can I release?

**Comment by mbechler** [comment]
Seems fine to me. I haven't seen any more issues with the patched version. Thanks.
