### ISSUE TITLE
Instructions on compiling for Windows

### ISSUE THREAD

**Issue by ARGYROU-MINAS** [alonbl/gnupg-pkcs11-scd#44]
Hello, 

I apologise in advance if the instructions are already somewhere and I didn't notice them, but I have already searched the Wiki section, the mailing lists on SourceForge etc., and haven't found anything.

How do I compile for Windows? My system is Windows 10 64-bit and I have Mingwin64, Cygwin4 and msys2 available.

Thanks!

**Comment by alonbl** [comment]
Hi,
In the past I made an effort to make it work, however, the socket protocol
of the assuan is not standard on Windows, several years have passed, I
guess it will not work.
In principle, you should build all gnupg libraries and components as
prerequisites and then build gnupg-pkcs11-scd the same way. It will be
easier to attempt building all WSL/linux using mingw-w64.
Regards,
Alon

**Comment by type4ranjan** [comment]
@ARGYROU-MINAS Were you able to compile and run it successfully on Windows?
If yes please share the steps, it would be very much appreciable.
Thanks in Advance!

**Comment by ARGYROU-MINAS** [comment]
@type4ranjan Tbh I don't have much experince with compiling, I am new to this. I tried Embarcadero but still didn't manage to compile it.
