### ISSUE TITLE
Provide Support for libassuan v3.x

### ISSUE THREAD

**Issue by ajh-** [alonbl/gnupg-pkcs11-scd#62]
When attempting to run `./configure`, currently receive `error: Need assuan-2` with libassuan v3.0.1 installed in environment.

**Comment by ametzler** [comment]
In Debian we have applied this patch: https://salsa.debian.org/alteholz/gnupg-pkcs11-scd/-/blob/master/debian/patches/libassuan-v3.patch?ref_type=heads

**Comment by alonbl** [comment]
Hi
This is simple enough, but does not apply as it probably tweaked with other patches as well.
Can you please check #56 if it works for you for me to apply? It should be safer to use and much more simple, if gnupg developers got it right this time.
Thanks,

**Comment by ametzler** [comment]
> Hi This is simple enough, but does not apply as it probably tweaked with other patches as well.

Yes that is on top of https://salsa.debian.org/alteholz/gnupg-pkcs11-scd/-/blob/master/debian/patches/pkg-config.patch?ref_type=heads which afaiui invokes pkg-config manually only as a hotfix to get a smaller change.

> Can you please check #56 if it works for you for me to apply? It should be safer to use and much more simple, if gnupg developers got it right this time. Thanks,

That works for me. (An it is indeed better, e,g. cross-compiling should work.)

Shouldn't this be changed to check the version?
```diff
-PKG_CHECK_MODULES([LIBASSUAN], [libassuan])
+PKG_CHECK_MODULES([LIBASSUAN], [libassuan >= 2])
```

**Comment by alonbl** [comment]
Hi @ametzler ,
Thank you for testing.
The conditional is not required as the pkg-config support is provided only in recent versions.
#56 was merged.
Alon
