### ISSUE TITLE
How to generate the same GPG key from the same keypair in an HSM

### ISSUE THREAD

**Issue by vigno88** [alonbl/gnupg-pkcs11-scd#64]
In a "non-hsm" environment, I could derive the same GPG from a unique RSA key by doing:
```
PEM2OPENPGP_TIMESTAMP=0 PEM2OPENPGP_USAGE_FLAGS=sign pem2openpgp "signer signer@test.com" < dev-key.pem  | gpg --import
```
This will always result in the same key in gpg.

Is it possible to replicate this using a key stored in an HSM? Whenever I try to `--full-generate-key` (while passing `--faked-system-time` to gpg) I get a different command.

Thanks,

Nathan AV

**Comment by alonbl** [comment]
I honestly do not, you can pick the same RSA key, but not sure how to create the exact public attributes.

**Comment by vigno88** [comment]
What does it even mean to pick the same RSA key? If two keys are generated from the same RSA key, then a blob is signed with each key. Both blob signatures cannot be verified with both public key even tough they are generated from the same RSA key.. (at least, that's what is happening to me when i'm trying)

**Comment by saper** [comment]
@vigno88 I don't fully understand what you mean my having "two keys generated from one key".

However:

if you generate a key on the HSM, you can be pretty sure it will be randomly generated. 

If you really need this, you can generate the key on the computer and then just import the key into HSM as many times as you need to. This defeats the purpose of using the HSM in the first place but I can imagine one could need this for testing.

Please also keep in mind that for some algorithms/key types the signatures are not reproducible. This means, if you sign the same text with the same key twice, you might get two different, but valid, signatures.

**Comment by vigno88** [comment]
I was able to implement my own solution that do not use gpg. Thanks a lot for your support! I will close the issue
