### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by 10ne1** [alonbl/gnupg-pkcs11-scd#65]
Hello

It's been quite a few years since the last release of [0.10.0](https://github.com/alonbl/gnupg-pkcs11-scd/releases/tag/gnupg-pkcs11-scd-0.10.0) and the master branch contains a fix de08969ae92d31b585d7055eb0734962f55a7282 for building against newer versions of libassuan >= 3.0 which works very nicely.

Can you please cut / tag a new release with the latest commit / fix? It's a pain to have to carry libassuan 2.0 around because of this package (I use Gentoo where libassuan v3 is stable).

Much appreciated!

**Comment by alonbl** [comment]
Done, thanks!
